name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: true

      - uses: oven-sh/setup-bun@v2

      - name: Install 🔧
        run: bun install

      - name: Build
        run: |
          bun run build --base='/${{ github.event.repository.name }}/'
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist